#ifndef MOD_GLFW_H
#define MOD_GLFW_H

/* STATIC EVENTS */
#define MOD_GLFW_STATIC_EVENT_QUERY_PRESENTATION_SUPPORT (1)
#define MOD_GLFW_STATIC_EVENT_GET_REQUIRED_INSTANCE_EXTENSIONS (2)

/* INSTANCE EVENTS */
#define MOD_GLFW_EVENT_POLL (1)
#define MOD_GLFW_EVENT_KEY_CALLBACK (2)
#define MOD_GLFW_EVENT_BUTTON_CALLBACK (3)
#define MOD_GLFW_EVENT_CURSOR_CALLBACK (4)

/* EXTENSIONS */
#define MOD_GLFW_EXT_TIMER_GET (1)
#define MOD_GLFW_EXT_TIMER_GET_PFN(pfn) double (*pfn)()
#define MOD_GLFW_EXT_TIMER_GET_VAL (2)
#define MOD_GLFW_EXT_TIMER_GET_VAL_PFN(pfn) unsigned long (*pfn)()
#define MOD_GLFW_EXT_TIMER_SET (3)
#define MOD_GLFW_EXT_TIMER_SET_PFN(pfn) void (*pfn)(double)
#define MOD_GLFW_EXT_GET_INST_PROC_ADDR (4)
#define MOD_GLFW_EXT_GET_INST_PROC_ADDR_PFN(pfn) void (*)() (*pfn)(void *, const char *)

#endif /* MOD_GLFW_H */
